services:
  - type: web
    name: clothes-store
    runtime: go
    rootDir: backend
    buildCommand: go build -o server ./cmd/server
    startCommand: ./server
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
